<?php 
    /* ESTAS CONSTANTES SIRVEN PARA SELECCIONAR 
    LAS CATEGORIAS DE LA BASE DE DATOS, PREFERENTEMENTE, NO CAMBIAR ESTE ARCHIVO YA QUE 
    TRABAJA EN CONJUNTO AL MODELO DE PROODUCTOS
    */
    DEFINE('CATG_CUEROS', 'CUEROS');
    DEFINE('CATG_TELAS', 'TELAS');
    DEFINE('CATG_FORROS', 'FORROS');
    DEFINE('CATG_HILOS', 'HILOS');
    DEFINE('CATG_ESPONJAS', 'ESPONJAS');
    DEFINE('CATG_CHAPITA', 'CHAPITA');
    DEFINE('CATG_PLANTA', 'PLANTA');
    DEFINE('CATG_PANTILLOS', 'PLANTILLOS');
    DEFINE('CATG_TACOS', 'TACOS');
    DEFINE('CATG_AGUJAS', 'AGUJAS');
    DEFINE('CATG_DRAMAS', 'DRAMAS');

